### ISSUE TITLE
Docker Compose version is outdated

### ISSUE THREAD

**Issue by bburtin** [AdnanHodzic/ansible-role-docker-compose-setup#1]
Thanks for offering this plugin to the Ansible community!  I noticed that your plugin installs a pretty old version of Docker Compose:

```
$ docker-compose --version
docker-compose version 1.17.1, build unknown
```

For better or worse, the official way to install Docker Compose is with curl:

https://docs.docker.com/compose/install/

Is there a plan to update the plugin so that it installs a specified version of Docker Compose or the latest version?

**Comment by AdnanHodzic** [comment]
I do plan to update it, but I'm not sure when that's going to happen :)

This project being open source and anyone being able to edit the code, I would encourage you to make the changes yourself and submit the PR to merge the changes back. Of course, I'm more then willing to help you in review process.

**Comment by bburtin** [comment]
This is what I ended up doing.  It works on my Ubuntu servers, but my devops chops aren't good enough to generalize the playbook so that it works on all platforms, checks the version before installing, supports multiple versions of Docker Compose, etc.
```
- name: Remove docker-compose if it was installed by apt
  apt:
    name: docker-compose
    state: absent
  become: yes

- name: Install docker-compose
  get_url:
    url : https://github.com/docker/compose/releases/download/1.26.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '755'
    force: yes  # Handle GitHub returning 304
  become: yes
```
